### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by riccardo-negri** [marcomole00/bioinformatics#1]
Hi @marcomole00,
first of all, thanks for your code, it helped me checking bioinfo exercise solutions.
I may suggest you to organize the repo in folders so it's more accessibile.
It would be also awesome if you could develop a GUI to interact with your script.
Thank you for you contribution to the bioinfo community.
Sincerely,
Riccardo

**Comment by marcomole00** [comment]
thanks for you interest in the repo,

the restructuring of the repo will be done when i'll have more scripts to add to the project.
Regarding the GUI i don't think i'll have the time to implement such a frivolous feature.
cheers

**Comment by riccardo-negri** [comment]
Cheers Mate
